// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.24.0
// 	protoc        v3.12.0
// source: pb/entity.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type EntityByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *EntityByIDRequest) Reset() {
	*x = EntityByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_entity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityByIDRequest) ProtoMessage() {}

func (x *EntityByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_entity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityByIDRequest.ProtoReflect.Descriptor instead.
func (*EntityByIDRequest) Descriptor() ([]byte, []int) {
	return file_pb_entity_proto_rawDescGZIP(), []int{0}
}

func (x *EntityByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type EntityByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entity *Entity `protobuf:"bytes,1,opt,name=entity,proto3" json:"entity,omitempty"`
}

func (x *EntityByIDResponse) Reset() {
	*x = EntityByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_entity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EntityByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntityByIDResponse) ProtoMessage() {}

func (x *EntityByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_entity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntityByIDResponse.ProtoReflect.Descriptor instead.
func (*EntityByIDResponse) Descriptor() ([]byte, []int) {
	return file_pb_entity_proto_rawDescGZIP(), []int{1}
}

func (x *EntityByIDResponse) GetEntity() *Entity {
	if x != nil {
		return x.Entity
	}
	return nil
}

type Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Entity) Reset() {
	*x = Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_entity_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_pb_entity_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_pb_entity_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Entity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pb_entity_proto protoreflect.FileDescriptor

var file_pb_entity_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x70, 0x62, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x23, 0x0a, 0x11, 0x45, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3c,
	0x0a, 0x12, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x06, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22, 0x2c, 0x0a, 0x06,
	0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0x50, 0x0a, 0x09, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x52, 0x50, 0x43, 0x12, 0x43, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x42, 0x79, 0x49, 0x44, 0x12, 0x19, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x04, 0x5a, 0x02,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_entity_proto_rawDescOnce sync.Once
	file_pb_entity_proto_rawDescData = file_pb_entity_proto_rawDesc
)

func file_pb_entity_proto_rawDescGZIP() []byte {
	file_pb_entity_proto_rawDescOnce.Do(func() {
		file_pb_entity_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_entity_proto_rawDescData)
	})
	return file_pb_entity_proto_rawDescData
}

var file_pb_entity_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pb_entity_proto_goTypes = []interface{}{
	(*EntityByIDRequest)(nil),  // 0: entity.EntityByIDRequest
	(*EntityByIDResponse)(nil), // 1: entity.EntityByIDResponse
	(*Entity)(nil),             // 2: entity.Entity
}
var file_pb_entity_proto_depIdxs = []int32{
	2, // 0: entity.EntityByIDResponse.entity:type_name -> entity.Entity
	0, // 1: entity.EntityRPC.EntityByID:input_type -> entity.EntityByIDRequest
	1, // 2: entity.EntityRPC.EntityByID:output_type -> entity.EntityByIDResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_entity_proto_init() }
func file_pb_entity_proto_init() {
	if File_pb_entity_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_entity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_entity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EntityByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_entity_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_entity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_entity_proto_goTypes,
		DependencyIndexes: file_pb_entity_proto_depIdxs,
		MessageInfos:      file_pb_entity_proto_msgTypes,
	}.Build()
	File_pb_entity_proto = out.File
	file_pb_entity_proto_rawDesc = nil
	file_pb_entity_proto_goTypes = nil
	file_pb_entity_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EntityRPCClient is the client API for EntityRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EntityRPCClient interface {
	EntityByID(ctx context.Context, in *EntityByIDRequest, opts ...grpc.CallOption) (*EntityByIDResponse, error)
}

type entityRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewEntityRPCClient(cc grpc.ClientConnInterface) EntityRPCClient {
	return &entityRPCClient{cc}
}

func (c *entityRPCClient) EntityByID(ctx context.Context, in *EntityByIDRequest, opts ...grpc.CallOption) (*EntityByIDResponse, error) {
	out := new(EntityByIDResponse)
	err := c.cc.Invoke(ctx, "/entity.EntityRPC/EntityByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EntityRPCServer is the server API for EntityRPC service.
type EntityRPCServer interface {
	EntityByID(context.Context, *EntityByIDRequest) (*EntityByIDResponse, error)
}

// UnimplementedEntityRPCServer can be embedded to have forward compatible implementations.
type UnimplementedEntityRPCServer struct {
}

func (*UnimplementedEntityRPCServer) EntityByID(context.Context, *EntityByIDRequest) (*EntityByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EntityByID not implemented")
}

func RegisterEntityRPCServer(s *grpc.Server, srv EntityRPCServer) {
	s.RegisterService(&_EntityRPC_serviceDesc, srv)
}

func _EntityRPC_EntityByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EntityByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EntityRPCServer).EntityByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/entity.EntityRPC/EntityByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EntityRPCServer).EntityByID(ctx, req.(*EntityByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _EntityRPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "entity.EntityRPC",
	HandlerType: (*EntityRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EntityByID",
			Handler:    _EntityRPC_EntityByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pb/entity.proto",
}
