load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")
load("@bazel_gazelle//:def.bzl", "gazelle")

# gazelle:prefix github.com/ekhabarov/blog-code-snippets/bazel-k8s-envoy
# gazelle:build_file_name BUILD,BUILD.bazel
gazelle(name = "gazelle")

